# -*- coding: utf-8 -*-
"""CircularBuffer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywz96YbugTtdyMJUALOkmwSvw8WA5YM3
"""

class CircularBuffer:

    def _init_(self, capacidad, elementos_iniciales=None):
        self.capacidad = capacidad
        self.buffer = [None] * capacidad
        self.cabeza = 0   # siguiente elemento a sacar
        self.cola = 0     # siguiente posición para insertar
        self.tamaño = 0

        if elementos_iniciales:
            for elemento in elementos_iniciales:
                self.push(elemento)

    def _str_(self):
        elementos = []
        for elemento in self:
            elementos.append(str(elemento))
        return "[" + ", ".join(elementos) + "]"

    def _len_(self):
        return self.tamaño

    def isEmpty(self):
        return self.tamaño == 0

    def _iter_(self):
        indice = self.cabeza
        contador = 0
        while contador < self.tamaño:
            yield self.buffer[indice]
            indice = (indice + 1) % self.capacidad
            contador += 1

    def _contains_(self, elemento):
        for el in self:
            if el == elemento:
                return True
        return False

    def push(self, elemento):
        if self.tamaño == self.capacidad:
            raise Exception("Buffer lleno")

        self.buffer[self.cola] = elemento
        self.cola = (self.cola + 1) % self.capacidad
        self.tamaño += 1

    def pop(self, index=None):
        if self.isEmpty():
            raise Exception("Buffer vacío")

        valor = self.buffer[self.cabeza]
        self.buffer[self.cabeza] = None
        self.cabeza = (self.cabeza + 1) % self.capacidad
        self.tamaño -= 1
        return valor

    def clear(self):
        self.buffer = [None] * self.capacidad
        self.cabeza = 0
        self.cola = 0
        self.tamaño = 0