# -*- coding: utf-8 -*-
"""Taller#1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTOgz9-ZzxT0rrM-UQwGm1N2DUOCtnJV
"""

class ArrayList:
    def __init__(self, initial_elements=None, capacity=10):
        if capacity <= 0:
            raise ValueError("La capacidad debe ser mayor que 0")
        self.capacity = capacity
        self.size = 0
        self.array = [None] * self.capacity

        if initial_elements is not None:
            for element in initial_elements:
                self.append(element)

    def isEmpty(self):
        return self.size == 0

    def append(self, element):
        if self.size == self.capacity:
            self._resize()
        self.array[self.size] = element
        self.size += 1

    def insert(self, index, element):
        if index < 0 or index > self.size:
            raise IndexError("Índice fuera de rango")
        if self.size == self.capacity:
            self._resize()
        for i in range(self.size, index, -1):
            self.array[i] = self.array[i - 1]
        self.array[index] = element
        self.size += 1

    def pop(self, index=-1):
        if self.isEmpty():
            raise IndexError("pop from empty list")
        if index < 0:
            index += self.size
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        removed = self.array[index]
        for i in range(index, self.size - 1):
            self.array[i] = self.array[i + 1]

        self.array[self.size - 1] = None
        self.size -= 1
        return removed

    def remove(self, element):
        for i in range(self.size):
            if self.array[i] == element:
                self.pop(i)
                return
        raise ValueError(f"{element} not in list")

    def clear(self):
        self.size = 0
        self.array = [None] * self.capacity

    def __len__(self):
        return self.size

    def __getitem__(self, index):
        if index < 0:
            index += self.size
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")
        return self.array[index]

    def __iter__(self):
        for i in range(self.size):
            yield self.array[i]

    def __contains__(self, element):
        for i in range(self.size):
            if self.array[i] == element:
                return True
        return False

    def _resize(self):
        self.capacity *= 2
        new_array = [None] * self.capacity
        for i in range(self.size):
            new_array[i] = self.array[i]
        self.array = new_array

    def __str__(self):
        return str([self.array[i] for i in range(self.size)])

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:

    def __init__(self, initial_elements=None):
        self.head = None
        self.tail = None  # Puntero al último elemento
        self.size = 0

        if initial_elements is not None:
            for element in initial_elements:
                self.append(element)

    def isEmpty(self):
        return self.head is None

    def append(self, data):
        new_node = Node(data)
        if self.isEmpty():
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node  # Actualizamos el tail
        self.size += 1

    def insert(self, index, data):
        if index < 0 or index > self.size:
            raise IndexError("Índice fuera de rango")

        if index == self.size:
            self.append(data)
            return

        new_node = Node(data)
        if index == 0:
            new_node.next = self.head
            self.head = new_node
        else:
            current = self.head
            for _ in range(index - 1):
                current = current.next
            new_node.next = current.next
            current.next = new_node
        self.size += 1

    def pop(self, index=-1):
        if self.isEmpty():
            raise IndexError("pop from empty list")
        if index < 0:
            index += self.size
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        if index == 0:
            removed = self.head.data
            self.head = self.head.next
            if self.head is None:  # Si la lista quedó vacía
                self.tail = None
        else:
            current = self.head
            for _ in range(index - 1):
                current = current.next
            removed = current.next.data
            current.next = current.next.next
            if current.next is None:  # Si eliminamos el último, actualizamos el tail
                self.tail = current
        self.size -= 1
        return removed

    def remove(self, data):
        current = self.head
        prev = None
        while current:
            if current.data == data:
                if prev is None:  # Remover la cabeza
                    self.head = current.next
                    if self.head is None:
                        self.tail = None
                else:
                    prev.next = current.next
                    if current.next is None:  # Remover la cola
                        self.tail = prev
                self.size -= 1
                return
            prev = current
            current = current.next
        raise ValueError(f"{data} not in list")

    def clear(self):
        self.head = None
        self.tail = None
        self.size = 0

    def __len__(self):
        return self.size

    def __getitem__(self, index):
        if index < 0:
            index += self.size
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")
        current = self.head
        for _ in range(index):
            current = current.next
        return current.data

    def __iter__(self):
        current = self.head
        while current:
            yield current.data
            current = current.next


    def __contains__(self, data):
        current = self.head
        while current:
            if current.data == data:
                return True
            current = current.next
        return False

    def __str__(self):
        return str([item for item in self])