# -*- coding: utf-8 -*-
"""Copia de Taller#1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zo3-CJHeJBUtMOnj5O3_pKMv_hCKNRcj
"""

class ArrayList:
    def __init__(self, capacity=10):
        if capacity <= 0:
            raise ValueError("La capacidad debe ser mayor que 0")
        self.capacity = capacity
        self.size = 0
        self.array = [None] * capacity

    def is_empty(self):
        return self.size == 0

    def add(self, element):
        if self.size == self.capacity:
            self._resize()
        self.array[self.size] = element
        self.size += 1

    def add_at(self, index, element):
        if index < 0 or index > self.size:
            raise IndexError("Índice fuera de rango")

        if self.size == self.capacity:
            self._resize()

        for i in range(self.size, index, -1):
            self.array[i] = self.array[i - 1]

        self.array[index] = element
        self.size += 1

    def get(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")
        return self.array[index]

    def remove_at(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        removed = self.array[index]
        for i in range(index, self.size - 1):
            self.array[i] = self.array[i + 1]

        self.array[self.size - 1] = None
        self.size -= 1
        return removed

    def _resize(self):
        self.capacity *= 2
        new_array = [None] * self.capacity
        for i in range(self.size):
            new_array[i] = self.array[i]
        self.array = new_array

    def __str__(self):
        return str([self.array[i] for i in range(self.size)])

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None
        self.size = 0

    def is_empty(self):
        return self.head is None

    def add(self, data):
        new_node = Node(data)
        if self.is_empty():
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node
        self.size += 1

    def add_at(self, index, data):
        if index < 0 or index > self.size:
            raise IndexError("Índice fuera de rango")

        new_node = Node(data)

        if index == 0:
            new_node.next = self.head
            self.head = new_node
        else:
            current = self.head
            for _ in range(index - 1):
                current = current.next
            new_node.next = current.next
            current.next = new_node

        self.size += 1

    def get(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        current = self.head
        for _ in range(index):
            current = current.next
        return current.data

    def remove_at(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        if index == 0:
            removed = self.head.data
            self.head = self.head.next
        else:
            current = self.head
            for _ in range(index - 1):
                current = current.next
            removed = current.next.data
            current.next = current.next.next

        self.size -= 1
        return removed

    def __str__(self):
        elements = []
        current = self.head
        while current:
            elements.append(current.data)
            current = current.next
        return str(elements)

#Prueba en la termina de Arraylist
print(" PRUEBAS ARRAYLIST ")

a = ArrayList()

a.add(4)
a.add(5)
a.add(6)
a.add(7)
print("Lista inicial:")
print(a)

a.add_at(2, 10)
print("Lista después de insert(2, 10):")
print(a)

a.remove_at(1)
print("Lista después de remove(5):")
print(a)

print("Elemento en índice 2:")
print(a.get(2))

print("¿Está vacío?")
print(a.is_empty())

print("Tamaño:")
print(a.size)

# Validaciones
try:
    a.get(20)
except IndexError as e:
    print("Error controlado:", e)


#Preuba en la terminal de Linkedlist
print("\n PRUEBAS LINKEDLIST ")

l = LinkedList()

for x in [4, 5, 6, 7, 8, 9]:
    l.add(x)

print("Lista inicial:")
print(l)

l.add(4)
print("Lista después de append(4):")
print(l)

l.add_at(1, 10)
print("Lista después de insert(1, 10):")
print(l)

l.remove_at(2)
print("Lista después de remove(5):")
print(l)

print("Elemento en índice 3:")
print(l.get(3))

print("Pop en índice 0:")
print(l.remove_at(0))

print("Lista final:")
print(l)

print("¿Está vacío?")
print(l.is_empty())

print("Tamaño:")
print(l.size)

# Validaciones
try:
    l.add_at(20, 99)
except IndexError as e:
    print("Error controlado:", e)