# -*- coding: utf-8 -*-
"""Talleres-Corte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMgSigu5Zp0_2wIGlPBaixNwPGilOJzD
"""

class Stack:

    def __init__(self, initial_elements=[]):
        self.elements = []
        for e in initial_elements:
            self.elements.append(e)

    def __str__(self):
        return str(self.elements)

    def __len__(self):
        return len(self.elements)

    def isEmpty(self):
        if len(self.elements) == 0:
            return True
        else:
            return False

    def peek(self):
        if self.isEmpty():
            return None
        return self.elements[-1]

    def __iter__(self):
        return iter(self.elements)

    def __contains__(self, element):
        if element in self.elements:
            return True
        else:
            return False

    def push(self, element):
        self.elements.append(element)

    def pop(self, index=-1):
        if self.isEmpty():
            return None
        return self.elements.pop(index)

class Queue:

    def __init__(self, initial_elements=[]):
        self.elements = []
        for e in initial_elements:
            self.elements.append(e)

    def __str__(self):
        return str(self.elements)

    def __len__(self):
        return len(self.elements)

    def isEmpty(self):
        if len(self.elements) == 0:
            return True
        else:
            return False

    def peek(self):
        if self.isEmpty():
            return None
        return self.elements[0]

    def __iter__(self):
        return iter(self.elements)

    def __contains__(self, element):
        if element in self.elements:
            return True
        else:
            return False

    def push(self, element):
        self.elements.append(element)

    def pop(self, index=0):
        if self.isEmpty():
            return None
        return self.elements.pop(index)

class Node:
    def __init__(self, element):
        self.element = element  # valor del nodo
        self.next = None        # puntero al siguiente nodo


class CircularList:

    def __init__(self, initial_elements=[]):
        self.head = None  # Puntero al primer nodo
        self._size = 0    #  conteo para la validacion de indices

        # iteramos directamente sobre la lista que entra por defecto
        for element in initial_elements:
            self.append(element)

    def __str__(self):
        if self.isEmpty():
            return "[]"

        elements = []
        current = self.head
        # recorremos hasta que el next sea nuevamente el head
        while True:
            elements.append(str(current.element))
            current = current.next
            if current == self.head:
                break

        return "[" + ", ".join(elements) + "]"

    def __len__(self):
        return self._size

    def __getitem__(self, index):
        if index < 0 or index >= self._size:
            raise IndexError("Error: el indice no existe")

        current = self.head
        for _ in range(index):
            current = current.next
        return current.element

    def isEmpty(self):
        return self._size == 0

    def __iter__(self):
        if self.isEmpty():
            return

        current = self.head
        while True:
            yield current.element
            current = current.next
            if current == self.head:
                break

    def __contains__(self, element):
        if self.isEmpty():
            return False

        current = self.head
        while True:
            if current.element == element:
                return True
            current = current.next
            if current == self.head:
                break

        return False

    def append(self, element):
        new_node = Node(element)

        if self.isEmpty():
            self.head = new_node
            new_node.next = self.head  # Apunta a si mismo
        else:
            current = self.head
            # Buscar el ultimo nodo
            while current.next != self.head:
                current = current.next

            # Conecta el nuevo nodo al final y luego apuntar su nex al head
            current.next = new_node
            new_node.next = self.head

        self._size += 1

    def add(self, index, element):
        if index < 0 or index > self._size:
            raise IndexError("Error: el indice no existe")

        new_node = Node(element)

        if index == 0:
            if self.isEmpty():
                self.head = new_node
                new_node.next = self.head
            else:
                # Si insertamos en la posicion 0 actualiza el ultimo nodo para que apunte al nuevo head
                current = self.head
                while current.next != self.head:
                    current = current.next

                new_node.next = self.head
                self.head = new_node
                current.next = self.head
        else:
            current = self.head
            for _ in range(index - 1):
                current = current.next

            new_node.next = current.next
            current.next = new_node

        self._size += 1

    def remove(self, element):
        if self.isEmpty():
            raise ValueError("Error: el elemento no existe en la coleccion")

        current = self.head
        prev = None

        while True:
            if current.element == element:
                # Caso 1: Es el unico elemento en la lista
                if self._size == 1:
                    self.head = None
                # Caso 2: El elemento a eliminar es el Head
                elif current == self.head:
                    last = self.head
                    while last.next != self.head:
                        last = last.next
                    self.head = current.next
                    last.next = self.head
                # Caso 3: Es un elemento en el medio o al final
                else:
                    prev.next = current.next

                self._size -= 1
                return

            prev = current
            current = current.next

            # si dimos la vuelta completa y no lo encontramos
            if current == self.head:
                break

        raise ValueError("Error: el elemento no existe en la coleccion")

    def pop(self, index):
        if index < 0 or index >= self._size:
            raise IndexError("Error: el indice no existe")

        # Si solo hay un elemento
        if self._size == 1:
            element = self.head.element
            self.head = None
            self._size -= 1
            return element

        # Si queremos eliminar el Head
        if index == 0:
            element = self.head.element
            last = self.head
            while last.next != self.head:
                last = last.next
            self.head = self.head.next
            last.next = self.head
            self._size -= 1
            return element

        # si queremos eliminar cualquier otro indice
        current = self.head
        for _ in range(index - 1):
            current = current.next

        element = current.next.element
        current.next = current.next.next
        self._size -= 1
        return element

    def clear(self):
        self.head = None
        self._size = 0